name: Admiral User Wiki Publish
concurrency: admiral-publish-user-wiki

env:
  repository: ${{ github.server_url }}/${{ github.repository }}/mywiki-event.wiki.git'
on:
  workflow_dispatch:
    inputs:
      environment: 
        description: Select the enviroment
        options:
        - d
        - p
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out wiki
        uses: actions/checkout@v2
        with:
          repository:  ${{repository}}
          ref: 'master'
          path: 'mywiki-event.wiki'
      - name: "Variable"
        run: | 
             echo `Repository :  ${{repository}}`
             echo `Environment :  ${{ github.event.inputs.environment }}`
       
